=== meveel25/Act2_LM/Act2_LM_Alvaro/XSD/biblioteca.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libros">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="libro" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="1"></xs:minLength>
                                                    <xs:maxLength value="50"></xs:maxLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="capitulos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="capitulo" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="titulo" >
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:minLength value="1"></xs:minLength>
                                                                        <xs:maxLength value="50"></xs:maxLength>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                                </xs:element>
                                                                <xs:element name="contenido">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="informacion" use="required">
                                                                            <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:pattern value="[hH][tT]{2}[pP][sS]?://[wW]{3}.*"/>
                                                                            </xs:restriction>
                                                                            </xs:simpleType>
                                                                        </xs:attribute>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="paginas" type="xs:nonNegativeInteger" use="required"></xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="indice">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="1"></xs:minLength>
                                                    <xs:maxLength value="200"></xs:maxLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="sinopsis">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="1"></xs:minLength>
                                                    <xs:maxLength value="1000"></xs:maxLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[L][0-9]{4}"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="tipo_clase" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="Novela"></xs:enumeration>
                                                <xs:enumeration value="Infantil"></xs:enumeration>
                                                <xs:enumeration value="DidÃ¡ctico"></xs:enumeration>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="paginas" type="xs:nonNegativeInteger" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="revistas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="revista" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="1"></xs:minLength>
                                                    <xs:maxLength value="50"></xs:maxLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="numero" type="xs:nonNegativeInteger"></xs:element>
                                        <xs:element name="indice">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="1"></xs:minLength>
                                                    <xs:maxLength value="200"></xs:maxLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="secciones_rev">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="seccion_rev" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="contenido">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="informacion" use="required">
                                                                            <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:pattern value="[hH][tT]{2}[pP][sS]?://[wW]{3}.*"/>
                                                                            </xs:restriction>
                                                                            </xs:simpleType>
                                                                        </xs:attribute>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="paginas" type="xs:nonNegativeInteger" use="required"></xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[R][0-9]{4}"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="tipo_clase" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="InformÃ¡tica"></xs:enumeration>
                                                <xs:enumeration value="CorazÃ³n"></xs:enumeration>
                                                <xs:enumeration value="Coches"></xs:enumeration>
                                                <xs:enumeration value="InvestigaciÃ³n"></xs:enumeration>
                                                <xs:enumeration value="Otras"></xs:enumeration>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="paginas" type="xs:nonNegativeInteger" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="periodicos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="periodico" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="secciones_per">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="seccion_per" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="articulos">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="articulo" minOccurs="1" maxOccurs="unbounded">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="contenido">
                                                                                            <xs:complexType>
                                                                                                <xs:attribute name="informacion" use="required">
                                                                                                    <xs:simpleType>
                                                                                                        <xs:restriction base="xs:string">
                                                                                                            <xs:pattern value="[hH][tT]{2}[pP][sS]?://[wW]{3}.*"/>
                                                                                                        </xs:restriction>
                                                                                                    </xs:simpleType>
                                                                                                </xs:attribute>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                    <xs:attribute name="autor" type="xs:string" use="required"></xs:attribute>
                                                                                </xs:complexType>                                                                            
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="tipo" use="required">
                                                                <xs:simpleType>
                                                                     <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="EconÃ³mica"></xs:enumeration>
                                                                        <xs:enumeration value="OpiniÃ³n"></xs:enumeration>
                                                                        <xs:enumeration value="Deportes"></xs:enumeration>
                                                                        <xs:enumeration value="Nacional"></xs:enumeration>
                                                                        <xs:enumeration value="Internacional"></xs:enumeration>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="indice">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="1"></xs:minLength>
                                                    <xs:maxLength value="200"></xs:maxLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[P][0-9]{4}"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="tipo_clase" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="Nacional"></xs:enumeration>
                                                <xs:enumeration value="Internacional"></xs:enumeration>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="fecha" type="xs:date" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== meveel25/Act2_LM/Act2_LM_Alvaro/XSD/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:noNamespaceSchemaLocation= "biblioteca.xsd">
    <libros>
        <libro id="L0001" tipo_clase="Novela" paginas="321">
            <titulo>La cabaña del lago</titulo>
            <capitulos>
                <capitulo paginas="20">
                    <titulo>La desaparición de Chloe</titulo>
                    <contenido informacion="http://www.biblioteca.com/lacasadellago/capitulo1.html"/>
                </capitulo>
                <capitulo paginas="32">
                    <titulo>Un vecino sospechoso</titulo>
                    <contenido informacion="http://www.biblioteca.com/lacasadellago/capitulo2.html"/>
                </capitulo>
                <capitulo paginas="45">
                    <titulo>Pruebas en el maletero</titulo>
                    <contenido informacion="http://www.biblioteca.com/lacasadellago/capitulo3.html"/>
                </capitulo>
            </capitulos>
            <indice>Madre e hija. Secuestro. Candidata a película de tarde.</indice>
            <sinopsis>
                Clara y la pequeña Chloe se retiran a pasar unos días en la cabaña del lago, 
                pero la desaparición de la hija destapará sospechas infundadas entre la comunidad.
            </sinopsis>
        </libro>

        <libro id="L0002" tipo_clase="Infantil" paginas="54">
            <titulo>Una lechuga en mi sopa</titulo>
            <capitulos>
                <capitulo paginas="6">
                    <titulo>¿Qué es esa cosa verde?</titulo>
                    <contenido informacion="http://www.biblioteca.com/unalechugaenmisopa/capitulo1.html"/>
                </capitulo>
                <capitulo paginas="5">
                    <titulo>¡No me gustan las verduras!</titulo>
                    <contenido informacion="http://www.biblioteca.com/unalechugaenmisopa/capitulo2.html"/>
                </capitulo>
                <capitulo paginas="18">
                    <titulo>Ahora seré más fuerte</titulo>
                    <contenido informacion="http://www.biblioteca.com/unalechugaenmisopa/capitulo3.html"/>
                </capitulo>
            </capitulos>
            <indice>Educación. Alimentación. Buenos hábitos.</indice>
            <sinopsis>
                Gael no quiere comer porque ha descubierto algo asqueroso en su sopa.
                Aunque no le gustan las verduras, pronto descubrirá el poder oculto
                que tienen estos alimentos, que solo unos elegidos pueden apreciar.
            </sinopsis>
        </libro>
    </libros>

    <revistas>
        <revista id="R0001" tipo_clase="Informática" paginas="86">
            <titulo>Midjourney Prompts</titulo>
            <numero>7</numero>
            <indice>Imágenes realistas. Arte. Fotoperiodismo inventado.</indice>
            <secciones_rev>
                <seccion_rev paginas="8">
                    <contenido informacion="http://www.biblioteca.com/midjourneyprompts/imageneslectores.html"/>
                </seccion_rev>
                <seccion_rev paginas="4">
                    <contenido informacion="http://www.biblioteca.com/midjourneyprompts/realidadoficcion.html"/>
                </seccion_rev>
                <seccion_rev paginas="10">
                    <contenido informacion="http://www.biblioteca.com/midjourneyprompts/derechosdeimagen.html"/>
                </seccion_rev>
            </secciones_rev>
        </revista>

        <revista id="R0002" tipo_clase="Corazón" paginas="86">
            <titulo>La vida en rosa</titulo>
            <numero>55</numero>
            <indice>Letizia Ortiz. Nacho Cano. Penélope Cruz. Dani Martín.</indice>
            <secciones_rev>
                <seccion_rev paginas="9">
                    <contenido informacion="http://www.biblioteca.com/lavidaenrosa/nuevasparejas.html"/>
                </seccion_rev>
                <seccion_rev paginas="4">
                    <contenido informacion="http://www.biblioteca.com/lavidaenrosa/famosostirandolabasura.html"/>
                </seccion_rev>
                <seccion_rev paginas="12">
                    <contenido informacion="http://www.biblioteca.com/lavidaenrosa/grandesmomentos.html"/>
                </seccion_rev>
                <seccion_rev paginas="5">
                    <contenido informacion="http://www.biblioteca.com/lavidaenrosa/escandalos.html"/>
                </seccion_rev>
            </secciones_rev>
        </revista>
    </revistas>

    <periodicos>
        <periodico id="P0001" tipo_clase="Nacional" fecha="2023-05-15">
            <secciones_per>
                <seccion_per tipo="Económica">
                    <articulos>
                        <articulo autor="Pepe Salmón">
                            <contenido informacion="http://www.biblioteca.com/eltablao/accionesenbancaespanola.html"/>
                        </articulo>
                        <articulo autor="Juan Pérez">
                            <contenido informacion="http://www.biblioteca.com/eltablao/inversionaplazofijo.html"/>
                        </articulo>
                        <articulo autor="Matilde Escalonilla">
                            <contenido informacion="http://www.biblioteca.com/eltablao/elorocomovalorseguro.html"/>
                        </articulo>
                    </articulos>
                </seccion_per>
                <seccion_per tipo="Opinión">
                    <articulos>
                        <articulo autor="Marta Cáceres">
                            <contenido informacion="http://www.biblioteca.com/eltablao/elcalormitoorealidad.html"/>
                        </articulo>
                        <articulo autor="Pedro Martínez">
                            <contenido informacion="http://www.biblioteca.com/eltablao/nuncaestaremospreparados.html"/>
                        </articulo>
                    </articulos>
                </seccion_per>
            </secciones_per>
            <indice>Paro. Elecciones. Guerra. Corrupción.</indice>
        </periodico>
        <periodico id="P0002" tipo_clase="Internacional" fecha="2023-05-10">
            <secciones_per>
                <seccion_per tipo="Deportes">
                    <articulos>
                        <articulo autor="Tom Crew">
                            <contenido informacion="http://www.biblioteca.com/thespacetimes/psgsfantasy.html"/>
                        </articulo>
                        <articulo autor="Mark Threepwood">
                            <contenido informacion="http://www.biblioteca.com/thespacetimes/50bestliverpoolplayersever.html"/>
                        </articulo>
                        <articulo autor="Ellen McRide">
                            <contenido informacion="http://www.biblioteca.com/thespacetimes/alookintomanchesterunited.html"/>
                        </articulo>
                    </articulos>
                </seccion_per>
                <seccion_per tipo="Internacional">
                    <articulos>
                        <articulo autor="Simon Brown">
                            <contenido informacion="http://www.biblioteca.com/thespacetimes/australiadoesntexist.html"/>
                        </articulo>
                        <articulo autor="Allan Preston">
                            <contenido informacion="http://www.biblioteca.com/thespacetimes/brazilneedsmoresamba.html"/>
                        </articulo>
                    </articulos>
                </seccion_per>
            </secciones_per>
            <indice>European Union. Canada. Climate change. Civil rights.</indice>
        </periodico>
    </periodicos>
</biblioteca>
